src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 */
class Products
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $info;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Positive
     * @Assert\Type("int")
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Positive
     * @Assert\Type("int")
     */
    private $point;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Type("int")
     */
    private $point_give;
    //
    /**
     * @ORM\OneToMany(targetEntity=OrdersDetail::class, mappedBy="products")
     */
    private $ordersDetails;

    /**
     * @ORM\ManyToMany(targetEntity=Parameters::class, mappedBy="products", fetch="EAGER")
     * @ORM\JoinTable(name="parameters_products")
     */
    private $parameters;

    /**
     * @ORM\OneToMany(targetEntity=CartDetail::class, mappedBy="product", orphanRemoval=true)
     */
    private $cartDetail;



    public function __construct()
    {
        $this->ordersDetails = new ArrayCollection();
        $this->parameters = new ArrayCollection();
        $this->cartDetail = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(string $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPoint(): ?int
    {
        return $this->point;
    }

    public function setPoint(?int $point): self
    {
        $this->point = $point;

        return $this;
    }

    public function getPointGive(): ?int
    {
        return $this->point_give;
    }

    public function setPointGive(?int $point_give): self
    {
        $this->point_give = $point_give;

        return $this;
    }

    /**
     * @return Collection<int, OrdersDetail>
     */
    public function getOrdersDetails(): Collection
    {
        return $this->ordersDetails;
    }

    public function addOrdersDetail(OrdersDetail $ordersDetail): self
    {
        if (!$this->ordersDetails->contains($ordersDetail)) {
            $this->ordersDetails[] = $ordersDetail;
            $ordersDetail->setProductId($this);
        }

        return $this;
    }

    public function removeOrdersDetail(OrdersDetail $ordersDetail): self
    {
        if ($this->ordersDetails->removeElement($ordersDetail)) {
            // set the owning side to null (unless already changed)
            if ($ordersDetail->getProductId() === $this) {
                $ordersDetail->setProductId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Parameters>
     */
    public function getParameters(): Collection
    {
        return $this->parameters;
    }


    public function setParameters(ArrayCollection $parameters)
    {
        $this->parameters = $parameters;

        return $this;
    }



    public function addParameter(Parameters $parameter): self
    {
        if (!$this->parameters->contains($parameter)) {
            $this->parameters[] = $parameter;
            $parameter->addProducts($this);
        }

        return $this;
    }

    public function removeParameter(Parameters $parameter): self
    {
        if ($this->parameters->removeElement($parameter)) {
            $parameter->removeProducts($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, CartDetail>
     */
    public function getCartDetail(): Collection
    {
        return $this->cartDetail;
    }

    public function addCartDetail(CartDetail $cartDetail): self
    {
        if (!$this->cartDetail->contains($cartDetail)) {
            $this->cartDetail[] = $cartDetail;
            $cartDetail->setProduct($this);
        }

        return $this;
    }

    public function removeCartDetail(CartDetail $cartDetail): self
    {
        if ($this->cartDetail->removeElement($cartDetail)) {
            // set the owning side to null (unless already changed)
            if ($cartDetail->getProduct() === $this) {
                $cartDetail->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\CartDetail;
use App\Entity\Users;
use App\Entity\Categories;
use App\Entity\Orders;
use App\Entity\OrdersDetail;
use App\Repository\CartRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\ProductsRepository;
use App\Repository\CartDetailRepository;
use App\Repository\CategoriesRepository;
use App\Repository\ParametersRepository;
use App\Repository\OrdersDetailRepository;
use App\Repository\OrdersRepository;
use App\Repository\UsersRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ClientController extends AbstractController
{
    public function __construct(
        ProductsRepository $productsRepository,
        PaginatorInterface $paginatorInterface,
        CategoriesRepository $categoriesRepository,
        ParametersRepository $parametersRepository,
        CartRepository $cartRepository,
        OrdersRepository $ordersRepository,
        OrdersDetailRepository $ordersDetailRepository,
        ManagerRegistry $managerRegistry,
        UsersRepository $usersRepository,
        MailerInterface $mailer,
        ValidatorInterface $validator,
        PaginatorInterface $paginator,
        CartDetailRepository $cartDetailRepository
    ) {
        $this->productsRepository = $productsRepository;
        $this->categoriesRepository = $categoriesRepository;
        $this->parametersRepository = $parametersRepository;
        $this->cartRepository = $cartRepository;
        $this->cartDetailRepository = $cartDetailRepository;
        $this->ordersDetailRepository = $ordersDetailRepository;
        $this->ordersRepository = $ordersRepository;
        $this->usersRepository = $usersRepository;
        $this->mailer = $mailer;
        $this->managerRegistry = $managerRegistry;
        $this->paginator = $paginator;
        $this->validator = $validator;
        $this->paginatorInterface = $paginatorInterface;
    }

    public function index(Request $request)
    {
        if ($this->isGranted('ROLE_CUSTOMER')) {
            $session = $request->getSession();
            $arrCart =  $session->get('cart');
            if ($arrCart != null) {
                $customer_id = $this->getUser()->getId();
                $check_cart = $this->cartRepository->findBy(['customer' => $customer_id]);
                if (!$check_cart) {
                    $cart = new Cart();
                    $cart->setCustomer($this->getUser());
                    $this->cartRepository->add($cart, true);
                    foreach ($arrCart as $product_id => $quantity) {
                        $product = $this->productsRepository->find($product_id);
                        $cartDetail = new CartDetail();
                        $cartDetail->setCart($cart);
                        $cartDetail->setProduct($product);
                        $cartDetail->setQuantity($quantity['quantity']);
                        $this->cartDetailRepository->add($cartDetail, true);
                    }
                    $session->remove('cart');
                }
            }
        }

        $product = $this->productsRepository->findAll();
        $categories = $this->categoriesRepository->findAll();
        $products = $this->paginatorInterface->paginate(
            $product,
            $request->query->getInt('page', 1),
            20
        );

        return $this->render('client/index.html.twig', [
            'products' => $products,
            'categories' => $categories,
        ]);
    }

    public function category(Request $request)
    {
        $name = $request->get('name');
        $min = $request->get('min');
        $max = $request->get('max');
        if ($request->get('category')) {
            $category = $request->get('category');
            $product = $this->productsRepository->findByNameCategory($category);
        } else {
            $product = $this->productsRepository->findAll();
        }
        if ($request->get('min') != null) {
            $product = $this->productsRepository->findProduct($category, $name, $min, $max);
        }
        $categories = $this->categoriesRepository->findAll();
        $params = $this->parametersRepository->findAll();
        // if (!$product) {
        //     // tao 1 trang k co san pham
        //     $referer = $request->headers->get('referer');
        //     return $this->redirect($referer);
        // }
        $products = $this->paginatorInterface->paginate(
            $product,
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('client/category.html.twig', [
            'products' => $products,
            'categories' => $categories,
            'category' => $category,
            'params' => $params,
        ]);
    }
    /**
     * @Route("/category/point", name="category_point", methods={"GET", "POST"})
     */
    public function categoryPoint(Request $request)
    {
        $name = $request->get('name');
        $min = $request->get('min');
        $max = $request->get('max');
        $product = $this->productsRepository->findBy(['price' => null]);
        if ($request->get('min') != null) {
            $product = $this->productsRepository->findProductPoint($name, $min, $max);
        }
        $categories = $this->categoriesRepository->findAll();
        $params = $this->parametersRepository->findAll();
        // if (!$product) {
        //     // tao 1 trang k co san pham
        //     $referer = $request->headers->get('referer');
        //     return $this->redirect($referer);
        // }
        $products = $this->paginatorInterface->paginate(
            $product,
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('client/category.html.twig', [
            'products' => $products,
            'categories' => $categories,
            'category' => "Point",
            'params' => $params,
        ]);
    }

    /**
     * @Route("/filter-product", name="filter_product", methods={"GET", "POST"})
     */
    public function filter(Request $request)
    {
        $name = $request->get('name');
        $min = $request->get('min');
        $max = $request->get('max');
        $category = $request->get('category');
        if ($request->isXmlHttpRequest()) {
            if ($category == "Point") {
                $product = $this->productsRepository->findProductPoint($name, $min, $max);
                // dd($product);
            } else {
                $product = $this->productsRepository->findProduct($category, $name, $min, $max);
            }
            $products = $this->paginatorInterface->paginate(
                $product,
                $request->query->getInt('page', 1),
                12
            );
            return $this->render('client/show_product.html.twig', [
                'products' => $products,
            ]);
        } else {
            if ($category == "Point") {
                return $this->categoryPoint($request);
            }
            return $this->category($request);
        }
    }

    public function product(Request $request)
    {
        $product_id = $request->get('product');
        $product = $this->productsRepository->find($product_id);
        return $this->render('client/product.html.twig', [
            'product' => $product,
        ]);
    }
    public function productByPoint(Request $request)
    {
        $product_id = $request->get('product');
        $product = $this->productsRepository->find($product_id);
        return $this->render('client/product.html.twig', [
            'product' => $product,
        ]);
    }
    /**
     * @Route("add-cart", name="add_to_cart", methods={"GET", "POST"})
     */
    public function addtocart(Request $request)
    {
        $product_id = $request->get('product_id');
        $quantity = $request->get('quantity');
        $product = $this->productsRepository->find($product_id);
        $cart = new Cart();
        if ($this->isGranted('ROLE_CUSTOMER')) {
            try {
                $customer_id = $this->getUser()->getId();
                $check_cart = $this->cartRepository->findBy(['customer' => $customer_id]);
                if (!$check_cart) {
                    $cart->setCustomer($this->getUser());
                    $this->cartRepository->add($cart, true);
                } else {
                    $cart = $check_cart[0];
                }

                $cart_id = $cart->getId();
                $checkProduct = $this->cartDetailRepository->findBy(['cart' => $cart_id, 'product' => $product_id]);
                if ($checkProduct) {
                    $currentQuantity = $checkProduct[0]->getQuantity();
                    $checkProduct[0]->setQuantity($currentQuantity + $quantity);
                    $this->cartDetailRepository->add($checkProduct[0], true);
                } else {
                    $cartDetail = new CartDetail();
                    $cartDetail->setCart($cart);
                    $cartDetail->setProduct($product);
                    $cartDetail->setQuantity($quantity);
                    $this->cartDetailRepository->add($cartDetail, true);
                }
                return new Response('success', 200);
            } catch (\Exception $e) {
                return new Response('error', 400);
            }
        } else {
            $check_product = $this->productsRepository->find($product_id);
            if($check_product == null){

templates/client/contact.html.twig
{% extends "client/base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/themify-icons/themify-icons.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/jquery-ui-1.12.1.custom/jquery-ui.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/contact_styles.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/contact_responsive.css')}}">
{% endblock %}
{% block javascripts %}
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
	<script src="{{asset('plugins/jquery-ui-1.12.1.custom/jquery-ui.js')}}"></script>
	<script src="{{asset('js/contact_custom.js')}}"></script>
{% endblock %}

{% block body %}
	<div class="container contact_container">
		<div class="row">
			<div
				class="col">

				<!-- Breadcrumbs -->

				<div class="breadcrumbs d-flex flex-row align-items-center">
					<ul>
						<li>
							<a href="index.html">Home</a>
						</li>
						<li class="active">
							<a href="#">
								<i class="fa fa-angle-right" aria-hidden="true"></i>Contact</a>
						</li>
					</ul>
				</div>

			</div>
		</div>

		<!-- Map Container -->

		<div class="row">
			<div class="col">
				<div id="google_map">
					<div class="map_container">
						<div id="map"></div>
					</div>
				</div>
			</div>
		</div>

		<!-- Contact Us -->

		<div class="row">

			<div class="col-lg-6 contact_col">
				<div class="contact_contents">
					<h1>Contact Us</h1>
					<p>There are many ways to contact us. You may drop us a line, give us a call or send an email, choose what suits you the most.</p>
					<div>
						<p>(800) 686-6688</p>
						<p>info.deercreative@gmail.com</p>
					</div>
					<div>
						<p>mm</p>
					</div>
					<div>
						<p>Open hours: 8.00-18.00 Mon-Fri</p>
						<p>Sunday: Closed</p>
					</div>
				</div>

				<!-- Follow Us -->

				<div class="follow_us_contents">
					<h1>Follow Us</h1>
					<ul class="social d-flex flex-row">
						<li>
							<a href="#" style="background-color: #3a61c9">
								<i class="fa fa-facebook" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#" style="background-color: #41a1f6">
								<i class="fa fa-twitter" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#" style="background-color: #fb4343">
								<i class="fa fa-google-plus" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="#" style="background-color: #8f6247">
								<i class="fa fa-instagram" aria-hidden="true"></i>
							</a>
						</li>
					</ul>
				</div>

			</div>

			<div class="col-lg-6 get_in_touch_col">
				<div class="get_in_touch_contents">
					<h1>Get In Touch With Us!</h1>
					<p>Fill out the form below to recieve a free and confidential.</p>
					<form action="post">
						<div>
							<input id="input_name" class="form_input input_name input_ph" type="text" name="name" placeholder="Name" required="required" data-error="Name is required.">
							<input id="input_email" class="form_input input_email input_ph" type="email" name="email" placeholder="Email" required="required" data-error="Valid email is required.">
							<input id="input_website" class="form_input input_website input_ph" type="url" name="name" placeholder="Website" required="required" data-error="Name is required.">
							<textarea id="input_message" class="input_ph input_message" name="message" placeholder="Message" rows="3" required data-error="Please, write us a message."></textarea>
						</div>
						<div>
							<button id="review_submit" type="submit" class="red_button message_submit_btn trans_300" value="Submit">send message</button>
						</div>
					</form>
				</div>
			</div>

		</div>
	</div>
{% endblock %}

templates/client/product.html.twig
{% extends "client/base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/themify-icons/themify-icons.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('plugins/jquery-ui-1.12.1.custom/jquery-ui.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/single_styles.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/single_responsive.css')}}">
{% endblock %}
{% block javascripts %}
	<script src="{{asset('js/single_custom.js')}}"></script>
	<script type="text/javascript">
		$( document ).ready(function() {
			$('.add_to_cart_button').click(function(e){
				e.preventDefault();
				let product_id = $(this).parent('div').find('.product-id').val();
				let quantity = $(this).parent('div').find('.quantity').val();
				$.ajax({
					url: "{{path('add_to_cart')}}",
					type: 'GET',
					data: {product_id, quantity},
				success: function(data) {
					$.notify("Thêm vào giỏ hàng thành công", "success");
				},
            	error: function(data) {
					$.notify("Có gì đó sai sai!", "error");;
				},
				})
			});
		})
		$(document).on('click', '.minus, .plus', function () {
			document.getElementById('quantity').value = document.getElementById('quantity_value').innerHTML;
		});
	</script>
{% endblock %}

{% block body %}
	<div class="container single_product_container">
		<div class="row">
			<div class="col">
				<div class="breadcrumbs d-flex flex-row align-items-center">
					<ul>
						<li>
							<a href="{{path('client_page')}}">Home</a>
						</li>
						<li>
							<a href="{{ path('category', {'category' : product.category.getName()}) }}">
								<i class="fa fa-angle-right" aria-hidden="true"></i>
								{{product.category.getName()}}</a>
						</li>
						<li class="active">
							<a href="{{path('product', {'product' : product.id})}}">
								<i class="fa fa-angle-right" aria-hidden="true"></i>
								{{product.name}}</a>
						</li>
					</ul>
				</div>

			</div>
		</div>
		<div class="row">
			<div class="col-lg-7">
				<div class="single_product_pics">
					<div class="row">
						<div class="col-lg-3 thumbnails_col order-lg-1 order-2">
							<div class="single_product_thumbnails">
								<img src="{{asset('uploads/images/' ~ product.image)}}" alt="" data-image="{{asset('uploads/images/' ~ product.image)}}" style="height:400px;width:400px">
							</div>
						</div>
						<div class="col-lg-9 image_col order-lg-2 order-1">
							<div class="single_product_image">
								<div class="single_product_image_background" style="background-image:url(images/single_2.jpg)"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-5">
				<div class="product_details">
					<div class="product_details_title">
						<h2>{{product.name}}</h2>
						<p>{{product.info}}</p>
					</div>
					<div class="free_delivery d-flex flex-row align-items-center justify-content-center">
						<span class="ti-truck"></span>
						<span>free delivery</span>
					</div>
					<div class="original_price"></div>
					{% if product.price %}
						<div class="product_price">Price: ${{product.price}}</div>
					{% else %}
						<div class="product_price">Point: ${{product.point}}</div>
					{% endif %}

					<ul class="star_rating">
						<li>
							<i class="fa fa-star" aria-hidden="true"></i>
						</li>
						<li>
							<i class="fa fa-star" aria-hidden="true"></i>
						</li>
						<li>
							<i class="fa fa-star" aria-hidden="true"></i>
						</li>
						<li>
							<i class="fa fa-star" aria-hidden="true"></i>
						</li>
						<li>
							<i class="fa fa-star-o" aria-hidden="true"></i>
						</li>
					</ul>
					<br><br>
					{% if product.pointGive %}
						<div class="">Point Give:
							{{product.pointGive}}</div>
					{% endif %}
					{# <form action="{{path('add_to_cart')}}" method="post"> #}
						<div class="quantity d-flex flex-column flex-sm-row align-items-sm-center">
							<span>Quantity:</span>
							<div class="quantity_selector">
								<span class="minus">
									<i class="fa fa-minus" aria-hidden="true"></i>
								</span>
								<span id="quantity_value">1</span>
								<span class="plus">
									<i class="fa fa-plus" aria-hidden="true"></i>
								</span>
							</div>
							<input type="hidden" class="product-id" name="product_id" value="{{product.id}}">
							<input type="hidden" class="quantity" id="quantity" name="quantity" value="1">
							<button type="submit" class="red_button add_to_cart_button">
								Add to card
							</button>
							<div class="product_favorite d-flex flex-column align-items-center justify-content-center"></div>
						</div>
					{# </form> #}
				</div>
			</div>
		</div>
	</div><!-- Tabs --><div class="tabs_section_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="tabs_container">
						<ul class="tabs d-flex flex-sm-row flex-column align-items-left align-items-md-center justify-content-center">
							<li class="tab active" data-active-tab="tab_1">
								<span>Description</span>
							</li>
							<li class="tab" data-active-tab="tab_2">
								<span>Additional Information</span>
							</li>
							<li class="tab" data-active-tab="tab_3">
								<span>Reviews (2)</span>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div
					class="col">

					<!-- Tab Description -->

					<div id="tab_1" class="tab_container active">
						<div class="row">
							<div class="col-lg-5 desc_col">
								<div class="tab_title">
									<h4>Description</h4>
								</div>
								<div class="tab_text_block">
									<h2>Pocket cotton sweatshirt</h2>
									<p>Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut...</p>
								</div>
								<div class="tab_image">
									<img src="images/desc_1.jpg" alt="">
								</div>
								<div class="tab_text_block">
									<h2>Pocket cotton sweatshirt</h2>
									<p>Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut...</p>
								</div>
							</div>
							<div class="col-lg-5 offset-lg-2 desc_col">
								<div class="tab_image">
									<img src="images/desc_2.jpg" alt="">
								</div>
								<div class="tab_text_block">
									<h2>Pocket cotton sweatshirt</h2>
									<p>Nam tempus turpis at metus scelerisque placerat nulla deumantos solicitud felis. Pellentesque diam dolor, elementum etos lobortis des mollis ut...</p>
								</div>
								<div class="tab_image desc_last">
									<img src="images/desc_3.jpg" alt="">
								</div>
							</div>
						</div>
					</div>

					<!-- Tab Additional Info -->

					<div id="tab_2" class="tab_container">
						<div class="row">
							<div class="col additional_info_col">
								<div class="tab_title additional_info_title">
									<h4>Additional Information</h4>
								</div>
								<p>COLOR:<span>Gold, Red</span>
								</p>
								<p>SIZE:<span>L,M,XL</span>
								</p>
							</div>
						</div>
					</div>

					<!-- Tab Reviews -->

					<div id="tab_3" class="tab_container">
						<div
							class="row">

							<!-- User Reviews -->

							<div class="col-lg-6 reviews_col">
								<div class="tab_title reviews_title">
									<h4>Reviews (2)</h4>
								</div>

								<!-- User Review -->

								<div class="user_review_container d-flex flex-column flex-sm-row">
									<div class="user">
										<div class="user_pic"></div>
										<div class="user_rating">
											<ul class="star_rating">
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star-o" aria-hidden="true"></i>
												</li>
											</ul>
										</div>
									</div>
									<div class="review">
										<div class="review_date">27 Aug 2016</div>
										<div class="user_name">Brandon William</div>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
									</div>
								</div>

								<!-- User Review -->

								<div class="user_review_container d-flex flex-column flex-sm-row">
									<div class="user">
										<div class="user_pic"></div>
										<div class="user_rating">
											<ul class="star_rating">
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star-o" aria-hidden="true"></i>
												</li>
											</ul>
										</div>
									</div>
									<div class="review">
										<div class="review_date">27 Aug 2016</div>
										<div class="user_name">Brandon William</div>
										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
									</div>
								</div>
							</div>

							<!-- Add Review -->

							<div class="col-lg-6 add_review_col">

								<div class="add_review">
									<form id="review_form" action="post">
										<div>
											<h1>Add Review</h1>
											<input id="review_name" class="form_input input_name" type="text" name="name" placeholder="Name*" required="required" data-error="Name is required.">
											<input id="review_email" class="form_input input_email" type="email" name="email" placeholder="Email*" required="required" data-error="Valid email is required.">
										</div>
										<div>
											<h1>Your Rating:</h1>
											<ul class="user_star_rating">
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star" aria-hidden="true"></i>
												</li>
												<li>
													<i class="fa fa-star-o" aria-hidden="true"></i>
												</li>
											</ul>
											<textarea id="review_message" class="input_review" name="message" placeholder="Your Review" rows="4" required data-error="Please, leave us a review."></textarea>
										</div>
										<div class="text-left text-sm-right">
											<button id="review_submit" type="submit" class="red_button review_submit_btn trans_300" value="Submit">submit</button>
										</div>
									</form>
								</div>

							</div>

						</div>
					</div>

				</div>
			</div>
		</div>

	</div>
{% endblock %}

templates/client/success_order.html.twig
{% extends "client/base.html.twig" %}
{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ asset('css/main_styles.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/core-style.css')}}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/responsive.css')}}">
{% endblock %}
{% block body %}
<div class="container-fluid  mt-100">
	<h3>Bạn đã order thành công vui lòng kiểm tra email</h3>
	<a href="{{path('client_page')}}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">continue shopping</a>

</div>
{% endblock %}